### PR TITLE
refactor!: environment variables _FLARUM_DIR as a flarum path

### PR DESCRIPTION
**Pull request by xxxxxliil**
BREAKING CHANGE: no more hard-coding /flarum/app as a flarum path

### CODE REVIEW

**Comment by Magicalex** [comment]
Why do you want to change the path in the container?

**Comment by xxxxxliil** [comment]
> Why do you want to change the path in the container?

Prepare for greater compliance with the FHS standards

**Comment by xxxxxliil** [comment]
I'm going to change the path to /var/www/flarum

**Comment by Magicalex** [comment]
> 
> 
> > Why do you want to change the path in the container?
> 
> Prepare for greater compliance with the FHS standards
> 
> https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

Can you be more specific?

**Comment by xxxxxliil** [comment]
> Can you be more specific?

What is it about?

**Comment by xxxxxliil** [comment]
> You want change the flarum path... Why?
> 
> Read this #47

It has nothing to do with shared hosting, it's just to make the location of flarum compatible with the FHS, not in the root directory

**Comment by Magicalex** [comment]
Sorry but it's useless breaking change

**Pull request closed without merging**
