### PR TITLE
Replace Chmod (very long) by a find then a chmod

### PR DESCRIPTION
**Pull request by monnierant**
Hi

I would like to suggest a new flag to allow ignore of the two Chmod command that take a very long time to run on a very big asset folder.

### CODE REVIEW

**Comment by hardware** [comment]
You should use `find` to apply permissions only when they are not correct. Because your condition is dangerous.

```
find /flarum ! -user $UID -print0 | xargs -0 -r chown $UID:$GID
```

Something like that. I use this technique with high volume of data in my mailserver docker image :

[https://github.com/hardware/mailserver/local/bin/run.sh#L607](https://github.com/hardware/mailserver/blob/0897756e7cf9aaf627765d15f997770d129a2510/rootfs/usr/local/bin/run.sh#L607)

**Comment by monnierant** [comment]
Could be great can we do it in this container ? Do you want me to do it in my merge pull ?

**Comment by hardware** [comment]
You can change your PR if you want. But I'm not sure about this part :

find /flarum ! **-user $UID** -print0

I don't know if it works with a UID, you have to test that. Otherwise, I think it's an elegant solution for your issue.

**Comment by monnierant** [comment]
Hi hardware i can do the test on my side it's okay for me.
The moste important part for me is to keep using your repo after that as you got a very clean and good team. So if i test it well will you add it into your repo ? (my solution was one that doesn't impact already in place containers)

**Comment by hardware** [comment]
And use `find` only for `/flarum`. This is not usefull for `/services`, `/var/log` and `/var/lib/nginx`.

**Comment by monnierant** [comment]
Yes i can redo it to get a very clean commit history.
Just a question i have do the find on all those folders are there was in the previous one this command:
chown -R $UID:$GID /flarum /services /var/log /var/lib/nginx
line 32 and the chmod for flarum folders on line 108
chown -R $UID:$GID /flarum

If you think it's not usefull i can do that of cource. Just tell me.

**Comment by Hydrog3n** [comment]
No for the redo you can use `git rebase --interactive`

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

:)

**Comment by Hydrog3n** [comment]
For the line 108 why @hardware do this again ? 🤔

Normaly composer is run with the good UID and GID so files doesn't change.

**Comment by hardware** [comment]
Thank you for your pull request. I commited my self because I need to make a test on our forum this morning with a fresh build of alpine, so I added your changes in the process.

Have a good day.

**Comment by monnierant** [comment]
Hi again.

Thanks for your time. No worry it's good to get it in prod.

PS: Merci les copain francais ;)

**Pull request closed without merging**
