### PR TITLE
Added ENV VAR setting for which port to run, flarum on inside the con…

### PR DESCRIPTION
**Pull request by askvortsov1**
…tainer.

### CODE REVIEW

**Comment by Hydrog3n** [comment]
Why do you want to change this? You just have to bind the port on run. `-p "xxxx:8888"

**Comment by askvortsov1** [comment]
I'm working on a SAML2 extension for flarum, and OneLogin's SAML toolkit checks to see that the SAMLResponse destination is the same as the port that Flarum is running on. Because it's php, it thinks that it's on 8888, and throws an exception. This gives users the option to run Flarum on a different port inside the container while preserving the default as 8888.

**Comment by Hydrog3n** [comment]
Ok, I don't know about SAML2 and stuff but it's weird because if it's an extension it's running on PHP so it's will be all the time the same port. I will wait for @Magicalex review but your changes see good for me.

**Comment by Magicalex** [comment]
I don't understand why SAML2 need check the port.
But i am ok with your change.

**Pull request merged**
