### PR TITLE
Startup add wait db live 

### LINKED ISSUE #82: Failure of flarum installation due to not waiting for the database to live when starting
I know https://github.com/mondediefr/docker-flarum#3---run-it , but I think to try to get two containers started in parallel

### PR DESCRIPTION
**Pull request by xxxxxliil**
Close #82

### CODE REVIEW

**Comment by Magicalex** [comment]
Nice solution

**Comment by xxxxxliil** [comment]
> Nice solution

Is there anything else I should prepare?

**Comment by Hydrog3n** [comment]
Hello, Thank you work. Sorry I'm not a hug fan of this. Because when we run composer we can use depend_on with a condition and an healthcheck
https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on

**Comment by xxxxxliil** [comment]
> Also, it's better to check has an external cmd if really need to do that. Everyone will have a different problem.

Do calls to pure PHP scripts count as external commands?

**Comment by xxxxxliil** [comment]
Now?

**Comment by Magicalex** [comment]
See https://github.com/mondediefr/docker-flarum/issues/82#issuecomment-860047054

**Pull request closed without merging**
